### ISSUE TITLE
Something wrong, but Idk why

### ISSUE THREAD

**Issue by felangga** [dwisiswant0/BitslerBOT#1]
SyntaxError: Unexpected token: u (baris 49, file "Code", proyek "Bitsler Auto Betting")

**Comment by felangga** [comment]
Errornya ini SyntaxError: Unexpected token: u (baris 49, file "Code", proyek "Bitsler Auto Betting")

**Comment by mhdabdur** [comment]
Yup, dapet pesan gitu juga "Something wrong, but Idk why" itu kesalahan dimana ya?

**Comment by felangga** [comment]
Servernya lagi down gan

**Comment by qafitmaksum** [comment]
masih down yaa??

**Comment by japsa56** [comment]
server masih down ya ?

**Comment by ihwanbjn** [comment]
Pengen nyoba tp gak tau caranya

**Comment by dwisiswant0** [comment]
## This means 2 possibilities:
**1. The API is in trouble
2. Your connection is problematic** (because it can't read the response from the API)

And this issue that happens is **number 1**.

**Comment by japsa56** [comment]
DOwn lagi ya bro ?

**Comment by ryuriin** [comment]
# BitslerBOT v1 (Beta)
  # @ 2017, dw1

Something wrong, but Idk why.

**Comment by erhaem** [comment]
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: x-requested-with, content-type
{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error","data":null}}

ini kenapa ya?

**Comment by felangga** [comment]
Gimana kabar? Masih error?

**Comment by jedsada00** [comment]
What is PHP? How to use bot
Video presentation
