### ISSUE TITLE
What program?

### ISSUE THREAD

**Issue by gvoze32** [dwisiswant0/BitslerBOT#3]
What program do you use to execute this script? I have git-bash and dunno what to do... Please explain me step to step and with detail. I can set the config file but dunno how to run this. Or pls in the next update make the GUI version, hehe thanks.

**Comment by kadeckb** [comment]
C......................M........................D

**Comment by dwisiswant0** [comment]
## READ [THIS](https://github.com/dwisiswant0/BitslerBOT/blob/v1.2/README.md) CAREFULLY.
