### ISSUE TITLE
error this line

### ISSUE THREAD

**Issue by rusuh90** [dwisiswant0/BitslerBOT#7]
https://github.com/dwisiswant0/BitslerBOT/blob/4a8e17e66ac3b9f79ba142021b76cc26719969ce/bitslerbot.lib.php#L34

**Comment by dwisiswant0** [comment]
What's error? Gimme a proof.

**Comment by rusuh90** [comment]
bisakah di setting lose maximal 3x-4x saja habis itu langsung tutup betting..?
